# railway.toml

[project]
name = "secondme"
region = "europe-west4"

[deploy]
auto_deploy = true
buildCommand = "pip install poetry && poetry install --no-dev"
startCommand = "python app.py"

[services.backend.env]
AIRTABLE_API_KEY = "${{shared.AIRTABLE_API_KEY}}"
DATABASE_PRIVATE_URL = "${{Postgres-hu8_.DATABASE_PRIVATE_URL}}"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
grok = "${{shared.grok}}"
groq_api_key = "${{shared.groq_api_key}}"
onedrive_client_id = "${{shared.onedrive_client_id}}"
onedrive_client_secret = "${{shared.onedrive_client_secret}}"
OPENAI_API_KEY = "${{shared.OPENAI_API_KEY}}"
pinecone_api_key = "${{shared.pinecone_api_key}}"